# Generated by Django 3.2 on 2023-07-12 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('event_title', models.CharField(max_length=255, null=True)),
                ('upload_date', models.DateField(auto_now=True)),
                ('event_category', models.CharField(choices=[('under18', 'under18'), ('under15', 'under15'), ('under13', 'under13'), ('open', 'open')], max_length=255, null=True)),
                ('event_rules', models.TextField(blank=True, null=True)),
                ('event_description', models.CharField(max_length=255, null=True)),
                ('event_trophies', models.ImageField(blank=True, null=True, upload_to='images')),
                ('event_trophies_name', models.CharField(blank=True, max_length=255, null=True)),
                ('event_date', models.DateField()),
                ('is_upcoming', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='EventResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name1', models.CharField(blank=True, max_length=255, null=True)),
                ('team_name2', models.CharField(blank=True, max_length=255, null=True)),
                ('team_score1', models.CharField(blank=True, max_length=255, null=True)),
                ('team_score2', models.CharField(blank=True, max_length=255, null=True)),
                ('result_description', models.CharField(blank=True, max_length=255, null=True)),
                ('result_short_description', models.CharField(blank=True, max_length=255, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='EventResult', to='events.events')),
            ],
            options={
                'verbose_name': 'Event Result',
                'verbose_name_plural': 'Event Results',
                'ordering': ['-pk'],
            },
        ),
    ]
