# Generated by Django 3.2 on 2023-07-17 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventresult',
            name='fixture',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='sport_type',
            field=models.CharField(choices=[('under18', 'under18'), ('under15', 'under15'), ('under13', 'under13'), ('open', 'open')], max_length=255, null=True),
        ),
    ]
