# Generated by Django 3.2 on 2023-07-19 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20230717_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='organised_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='eventresult',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='events.events'),
        ),
    ]
